// export const manufacturers = [
//   "小米su7 XIAOMI SU7",
//   "奥迪 Audi",
//   "宝马 BMW",
//   "奔驰 Mercedes-Benz",
//   "丰田 Toyota",
//   "大众 Volkswagen",
//   "福特 Ford",
//   "本田 Honda",
//   "特斯拉 Tesla",
//   "比亚迪 BYD",
//   "吉利 Geely",
//   "奇瑞 Chery",
//   "红旗 Hongqi",
//   "雪佛兰 Chevrolet",
//   "现代 Hyundai",
//   "起亚 Kia",
//   "日产 Nissan",
//   "标致 Peugeot",
//   "雪铁龙 Citroën",
//   "捷豹 Jaguar",
//   "路虎 Land Rover",
//   "保时捷 Porsche",
//   "法拉利 Ferrari",
//   "兰博基尼 Lamborghini",
//   "宾利 Bentley",
//   "劳斯莱斯 Rolls-Royce"
  
// ];
export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "关于",
    links: [
      { title: "主要业务", url: "/" },
      { title: "多项流程", url: "/" },
      { title: "租车条款", url: "/" },
      { title: "业务关系", url: "/" },
    ],
  },
  {
    title: "xxx有限责任公司",
    links: [
      { title: "测试文本0", url: "/" },
      { title: "测试文本1", url: "/" },
      { title: "测试文本2", url: "/" },
      { title: "测试文本3", url: "/" },
    ],
  },
  {
    title: "联系我们",
    links: [
      { title: "测试文本4", url: "/" },
      { title: "测试文本5", url: "/" },
      { title: "测试文本6", url: "/" },
      { title: "测试文本7", url: "/" },
    ],
  },
];
